apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: airflow-dag-processor
  namespace: airflow-core
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: airflow-dag-processor
  template:
    metadata:
      annotations:
        argocd.argoproj.io/sync-wave: "3"
      labels:
        app: airflow-dag-processor
    spec:
      serviceAccountName: airflow-scheduler
      nodeSelector:
        workload: airflow-core
      tolerations:
        - key: dedicated
          operator: Equal
          value: airflow-core
          effect: NoSchedule
      containers:
        - name: dag-processor
          image: apache/airflow:3.0.0-python3.12
          command: ["airflow", "dag-processor"]
          envFrom:
            - configMapRef:
                name: airflow-config
            - secretRef:
                name: airflow-secret
          volumeMounts:
            - name: airflow-logs
              mountPath: /home/airflow/logs
            - name: dags
              mountPath: /home/airflow/dags
            - name: custom-logging
              mountPath: /opt/airflow/custom_logging
              readOnly: true
          resources:
            requests:
              cpu: 200m
              memory: 384Mi
            limits:
              cpu: 800m
              memory: 768Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 50000

      volumes:
        - name: airflow-logs
          persistentVolumeClaim:
            claimName: logs-local-pvc
        - name: dags
          persistentVolumeClaim:
            claimName: dags-pvc
        - name: custom-logging
          configMap:
            name: airflow-custom-logging
